name: Docker Publish
on: release

jobs:
    docker-push:
        runs-on: ubuntu-latest
        steps:
         - name: Get Code
           uses: actions/checkout@v3
         - name: Psuh to Docker hub
           uses: docker/login-action@v3
           with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
         - name: Build and push
           uses: docker/build-push-actions@v4
           with:
            context: .
            file: ./Dockerfile
            push: true
            tags: latest
             
